name: Chats
version: '${version}'
main: me.kallix.chats.Chats
api-version: 1.19
depend:
  - PlayerDataAPI
commands:
  chatcolor:
    description: "Change your display name color in chat!"
  hug:
    description: "Hug people :)"
  kiss:
    description: "Kiss people :v"
  strike:
    description: "Strike people"
  uwu:
    description: "UwU people"
